### ISSUE TITLE
Tech Stack of choice??

### ISSUE THREAD

**Issue by ShaunWMusic** [BoroDevMeetup/jobsite-ui#2]
Please leave a comment below of the tech stack of choice that we should use for building out the UI.

**Comment by daemyonc** [comment]
Angular, Vue, Svelte, or I guess React(my least favorite).

**Comment by ShaunWMusic** [comment]
I'm most fluent in Ember.js && React. so one of those two will be my vote
>Angular, Vue, Svelte, or I guess React(my least favorite).

**Comment by christianzoll** [comment]
I'm most fluent in React but my vote's for something beside's it for learning's sake.

**Comment by TrevorLocke** [comment]
I wouldnt mind helping. I'm still learning React but willing to do what i can

**Comment by daemyonc** [comment]
I can work with React or Ember would be fine too.

**Comment by robhenley** [comment]
I don't know how much time I can actually commit but my vote would be for React mostly because it's everywhere and one can always learn from differing approaches.
